map_server:
  ros__parameters:
    use_sim_time: true
    # yaml_filename은 환경 변수나 launch 파일에서 설정
    # 예: yaml_filename: $(find tb3_multi_robot)/maps/map.yaml
    yaml_filename: ""  # launch 파일에서 설정 필요